### ISSUE TITLE
Image format

### ISSUE THREAD

**Issue by Ko-Sit** [jimouris/parallel-convolution#1]
Does this program supports any other formats  like  jpeg/bmp? And maybe i do smth wrong, but i cant open blurred raw image after program processing. Could you help me to understand what's the reason of it?

**Comment by jimouris** [comment]
No it does not support jpg/bmp, it supports raw images. Try with [this](https://github.com/jimouris/parallel-convolution/blob/master/waterfall_1920_2520.raw) image. 
It is probably a problem with your raw image viewer. (Try ImageJ).

**Comment by MuhammadAhmed8** [comment]
Does this program supports other raw formats such as CR2, dng, etc. I cant file any other image with .raw extension on the internet. Could u please help?

**Comment by jimouris** [comment]
Hi, no, currently it only supports RAW images but I think you can maybe convert a PNG to a RAW. I'm not sure though because it's been a few years since I developed this project.

**Comment by MuhammadAhmed8** [comment]
Well apparently no converter is converting to just .raw. Anyways thank you.
