### ISSUE TITLE
 Problem viewing the image

### ISSUE THREAD

**Issue by picupicu** [jimouris/parallel-convolution#3]
Hello,

when I run the various programs (mpi and mpi + omp) with any image in .raw format in this case I downloaded a .RW2 image, after the program runs the created image it is not possible to open it, as if it were not created correctly. I also used the .raw file present on git but it is already corrupt as no raw image program reads it to me.

What am I doing wrong?

**Comment by picupicu** [comment]
when I compile I get this warning:

 warning: implicit declaration of function ‘divide_rows’ [-Wimplicit-function-declaration]
   57 |                 row_div = divide_rows(height, width, num_processes);

**Comment by jimouris** [comment]
Can you try to open it with a program called ImageJ? I think not all image formats are compatible.
